# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceOrigin.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from . import button_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(667, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 210, 181, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.table_output = QtWidgets.QTableWidget(self.centralwidget)
        self.table_output.setGeometry(QtCore.QRect(30, 240, 481, 241))
        self.table_output.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_output.setWordWrap(True)
        self.table_output.setObjectName("table_output")
        self.table_output.setColumnCount(0)
        self.table_output.setRowCount(0)
        self.table_output.horizontalHeader().setVisible(False)
        self.table_output.verticalHeader().setVisible(True)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 210, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.text_input = QtWidgets.QTextEdit(self.centralwidget)
        self.text_input.setGeometry(QtCore.QRect(30, 20, 481, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.text_input.sizePolicy().hasHeightForWidth())
        self.text_input.setSizePolicy(sizePolicy)
        self.text_input.setSizeIncrement(QtCore.QSize(10, 10))
        self.text_input.setMouseTracking(False)
        self.text_input.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.text_input.setObjectName("text_input")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 210, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(540, 60, 101, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.read_file_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/blue_spot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.read_file_button.setIcon(icon)
        self.read_file_button.setObjectName("read_file_button")
        self.verticalLayout.addWidget(self.read_file_button)
        self.analysis_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.analysis_button.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/purple_spot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analysis_button.setIcon(icon1)
        self.analysis_button.setObjectName("analysis_button")
        self.verticalLayout.addWidget(self.analysis_button)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(550, 300, 91, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.save_file_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.save_file_button.setIcon(icon)
        self.save_file_button.setObjectName("save_file_button")
        self.verticalLayout_2.addWidget(self.save_file_button)
        self.mode_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/yellow_spot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mode_button.setIcon(icon2)
        self.mode_button.setObjectName("mode_button")
        self.verticalLayout_2.addWidget(self.mode_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Target,  Opinion,  Rating"))
        self.pushButton_3.setText(_translate("MainWindow", "Sen Rating"))
        self.pushButton.setText(_translate("MainWindow", "Sentences"))
        self.read_file_button.setText(_translate("MainWindow", "Read File"))
        self.analysis_button.setText(_translate("MainWindow", "Analysis"))
        self.save_file_button.setText(_translate("MainWindow", "Save File"))
        self.mode_button.setText(_translate("MainWindow", "  Mode  "))
